export const BRANDS = [
    "Apple",
    "Samsung",
    "Dell",
    "Sony",
    "Nintendo",
    "GoPro",
    "Amazon",
    "Logitech",
    "Cotton On",
    "Levi's",
    "H&M",
    "Zara",
    "Nike",
    "Adidas",
    "Ray-Ban",
    "Casio",
    "Samsonite",
    "IKEA",
    "Philips",
    "Nespresso",
    "Tempur",
    "Sheridan",
    "Philips Hue",
    "MUJI",
    "Tefal",
    "Roborock",
    "The Ordinary",
    "Estee Lauder",
    "MAC",
    "Oral-B",
    "Philips",
    "OGX",
    "La Roche-Posay",
    "Dior",
    "Yankee Candle",
    "Centrum",
    "Starbucks",
    "Bertolli",
    "Lindt",
    "Barilla",
    "Ito En",
    "Lululemon",
    "Bowflex",
    "Salomon",
    "Butterfly",
    "Coleman",
    "FitSimplify",
    "Renpho",
    "Other"
] as const;

export const SIZE_OPTIONS = ["S", "M", "L", "XL"] as const;
